assert_lefthook_installed: true
pre-commit:
  commands:
    create-extensions-list:
      run: './scripts/create-extensions-list.ts && git add {files}'
      files: 'echo ./extension-list.json'
    verify-metadata:
      run: './scripts/verify-metadata.ts'
